// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_PostOrders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=errno,proto3" json:"errno,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostOrders.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostOrders.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x5d, 0x4f, 0x2f, 0x97, 0xc1, 0x6a, 0x10, 0x3d, 0x15, 0x61, 0x4d, 0x95, 0x6a, 0x05,
	0x6d, 0x6d, 0x2d, 0x52, 0x29, 0x9b, 0x5e, 0x31, 0xee, 0x10, 0x02, 0x26, 0x13, 0x67, 0xa2, 0xe8,
	0xbf, 0x97, 0x6c, 0x56, 0xac, 0xbc, 0x6a, 0xf7, 0x3d, 0xe6, 0x31, 0xdf, 0x1b, 0xb8, 0x18, 0x85,
	0x27, 0xbe, 0xa6, 0xaf, 0x97, 0x7e, 0x7c, 0xa3, 0xdf, 0xd7, 0x45, 0x17, 0x4f, 0x5b, 0x76, 0x7d,
	0xf7, 0x2a, 0xec, 0x54, 0x3e, 0xdd, 0x23, 0xeb, 0xf4, 0x20, 0x81, 0x44, 0x8b, 0x3b, 0xc8, 0x3c,
	0xbd, 0x7f, 0x90, 0x4e, 0x78, 0x09, 0xa0, 0xa4, 0xda, 0xf1, 0xf0, 0xdc, 0x85, 0xad, 0xb1, 0xa6,
	0xcc, 0x7d, 0x9e, 0x9c, 0x2a, 0x20, 0xc2, 0x41, 0xc3, 0xe1, 0x7b, 0xbb, 0x6f, 0x4d, 0x79, 0xe4,
	0xe3, 0xbf, 0xa8, 0x61, 0xe3, 0x49, 0x47, 0x1e, 0x94, 0xf0, 0x04, 0xd6, 0x24, 0xd2, 0x6b, 0x9b,
	0xa2, 0x49, 0xe1, 0x31, 0x1c, 0x92, 0xc8, 0xc0, 0x31, 0x98, 0xfb, 0x45, 0xe0, 0x19, 0x6c, 0x78,
	0x26, 0x98, 0x57, 0xad, 0xac, 0x29, 0x57, 0x3e, 0x8b, 0xba, 0x0a, 0x37, 0x4f, 0x90, 0xdd, 0x2f,
	0xf0, 0x58, 0x03, 0xfc, 0xb1, 0xa2, 0x75, 0xff, 0xb4, 0x70, 0xa9, 0xc2, 0xf9, 0xd5, 0x8e, 0x89,
	0x05, 0xb3, 0xd8, 0x6b, 0xd6, 0xf1, 0x24, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x42,
	0xb8, 0xed, 0x31, 0x01, 0x00, 0x00,
}
