// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_GetHouses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Aid                  string   `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Sd                   string   `protobuf:"bytes,2,opt,name=sd,proto3" json:"sd,omitempty"`
	Ed                   string   `protobuf:"bytes,3,opt,name=ed,proto3" json:"ed,omitempty"`
	Sk                   string   `protobuf:"bytes,4,opt,name=sk,proto3" json:"sk,omitempty"`
	P                    string   `protobuf:"bytes,5,opt,name=p,proto3" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *Request) GetSd() string {
	if m != nil {
		return m.Sd
	}
	return ""
}

func (m *Request) GetEd() string {
	if m != nil {
		return m.Ed
	}
	return ""
}

func (m *Request) GetSk() string {
	if m != nil {
		return m.Sk
	}
	return ""
}

func (m *Request) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CurrentPage          int64    `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPage            int64    `protobuf:"varint,5,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Response) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetHouses.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetHouses.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0xdf, 0xb4, 0xdb, 0xdd, 0xb7, 0x63, 0x11, 0x19, 0x64, 0x09, 0x8a, 0xb8, 0xf6, 0xe4,
	0x29, 0x82, 0x7e, 0x06, 0xd1, 0xe3, 0x92, 0x9b, 0x78, 0x90, 0xb8, 0x1d, 0xca, 0xb2, 0xdb, 0x26,
	0x26, 0xa9, 0xf8, 0x29, 0xfc, 0xcc, 0xb2, 0x93, 0xe8, 0x49, 0x4f, 0x9d, 0xe7, 0x0f, 0x7d, 0xc8,
	0x0f, 0xce, 0x9d, 0xb7, 0xd1, 0xde, 0xd0, 0x87, 0x19, 0xdc, 0x9e, 0xbe, 0xbf, 0x8a, 0x5d, 0x5c,
	0xf6, 0x56, 0x0d, 0xdb, 0x8d, 0xb7, 0x2a, 0xf8, 0x77, 0xf5, 0x40, 0xf1, 0xd1, 0x4e, 0x81, 0x42,
	0xfb, 0x04, 0x0b, 0x4d, 0x6f, 0x13, 0x85, 0x88, 0x27, 0x50, 0x9a, 0x6d, 0x27, 0xc5, 0x4a, 0x5c,
	0xd7, 0xfa, 0x70, 0xe2, 0x31, 0x14, 0xa1, 0x93, 0x05, 0x1b, 0x45, 0x60, 0x4d, 0x9d, 0x2c, 0x93,
	0xa6, 0x94, 0xef, 0xe4, 0x2c, 0xe7, 0x3b, 0x6c, 0x40, 0x38, 0x59, 0xb1, 0x14, 0xae, 0xfd, 0x14,
	0xf0, 0x5f, 0x53, 0x70, 0x76, 0x0c, 0x84, 0xa7, 0x50, 0x91, 0xf7, 0xa3, 0xcd, 0xbf, 0x4f, 0x02,
	0x97, 0x30, 0x27, 0xef, 0x87, 0xd0, 0xe7, 0x91, 0xac, 0x10, 0x61, 0xd6, 0x99, 0x68, 0x78, 0xaa,
	0xd1, 0x7c, 0xe3, 0x15, 0x34, 0x9b, 0xc9, 0x7b, 0x1a, 0xe3, 0x8b, 0x33, 0x3d, 0xf1, 0x6c, 0xa9,
	0x8f, 0xb2, 0xb7, 0x36, 0x3d, 0xe1, 0x05, 0x40, 0xb4, 0xd1, 0xec, 0x53, 0xa1, 0xe2, 0x42, 0xcd,
	0xce, 0x21, 0xbe, 0x7d, 0x86, 0xc5, 0x7d, 0x82, 0x82, 0x6b, 0xa8, 0x7f, 0x18, 0xe0, 0xa5, 0xfa,
	0x1d, 0x8e, 0xca, 0x64, 0xce, 0x56, 0x7f, 0x17, 0xd2, 0xf3, 0xda, 0x7f, 0xaf, 0x73, 0xe6, 0x7c,
	0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x9e, 0x7a, 0x59, 0x86, 0x01, 0x00, 0x00,
}
